table Fact_Inventory
	lineageTag: 81e48810-7212-4214-bf03-882299800001

	column Store_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 81e48810-7212-4214-bf03-882299800002
		summarizeBy: none
		sourceColumn: Store_ID

	column Product_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 81e48810-7212-4214-bf03-882299800003
		summarizeBy: none
		sourceColumn: Product_ID

	column Quantity_In_Stock
		dataType: int64
		formatString: #,##0
		lineageTag: 81e48810-7212-4214-bf03-882299800004
		summarizeBy: sum
		sourceColumn: Quantity_In_Stock

	partition Fact_Inventory = m
		mode: import
		source = 
			let
				Source = Excel.Workbook(File.Contents(FilePath), null, true),
				stocks_Table = Source{[Item="stocks",Kind="Sheet"]}[Data],
				#"Promoted Headers" = Table.PromoteHeaders(stocks_Table, [PromoteAllScalars=true]),
				#"Filtered Blank Rows" = Table.SelectRows(#"Promoted Headers", each [store_id] <> null and [store_id] <> ""),
				#"Renamed Columns" = Table.RenameColumns(#"Filtered Blank Rows", {{"store_id", "Store_ID"}, {"product_id", "Product_ID"}, {"quantity", "Quantity_In_Stock"}}),
				#"Changed Types" = Table.TransformColumnTypes(#"Renamed Columns", {{"Store_ID", Int64.Type}, {"Product_ID", Int64.Type}, {"Quantity_In_Stock", Int64.Type}})
			in
				#"Changed Types"
